environment:
  CIBW_BEFORE_BUILD: scripts\build-libsrtp.bat
  CIBW_SKIP: cp27-* cp33-* cp34-* pp27-*
  CIBW_TEST_COMMAND: python -m unittest discover -s {project}/tests
  CL: /I%TEMP%\libsrtp.install\include
  LINK: /LIBPATH:%TEMP%\libsrtp.install\lib
install:
  - cmd: C:\Python36-x64\python.exe -m pip install cibuildwheel
build_script:
  - cmd: C:\Python36-x64\python.exe -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing wheelhouse/*.whl"
      }
