dist: xenial
env:
  global:
    - CIBW_BEFORE_BUILD=".travis/build-libsrtp"
    - CIBW_ENVIRONMENT="CFLAGS=-I/tmp/libsrtp/include LDFLAGS=-L/tmp/libsrtp/lib"
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - CIBW_TEST_COMMAND="python3 -m unittest discover -s {project}/tests"
install: source .travis/install
language: python
matrix:
  include:
  - env: BUILD=sdist
  - env: BUILD=wheel
    services: docker
  - env: BUILD=wheel
    language: generic
    os: osx
python: "3.7"
script: .travis/script
sudo: true
